CHARACTER_BONE_MAPS = {  # (HL2, TF2, SSB4, SSBU)
    "Common": (
        True,  # ClavicleC
        True,  # LegC
        [
            # System Bones
            ("Trans", "Trans", "TransN", "Trans"),
            ("Rot", "Rot", "RotN", "Rot"),
            ("Throw", "Throw", "ThrowN", "Throw"),
            # Standard Bones
            ("ValveBiped.Bip01_Pelvis", "bip_pelvis", "HipN", "Hip"),
            ("ValveBiped.Bip01_Spine", "bip_spine_0", "WaistN", "Waist"),
            ("ValveBiped.Bip01_Spine1", "bip_spine_1", "BustN", "Bust"),
            ("ValveBiped.Bip01_Neck1", "bip_neck", "NeckN", "Neck"),
            ("ValveBiped.Bip01_Head1", "bip_head", "HeadN", "Head"),
            ("ValveBiped.Bip01_Spine2", "bip_spine_2", "CShoulderN", "ClavicleC"),
            ("ValveBiped.Bip01_L_Clavicle", "bip_collar_L", "LShoulderN", "ClavicleL"),
            ("ValveBiped.Bip01_R_Clavicle", "bip_collar_R", "RShoulderN", "ClavicleR"),
            ("ValveBiped.Bip01_L_UpperArm", "bip_upperArm_L", "LShoulderJ", "ShoulderL"),
            ("ValveBiped.Bip01_R_UpperArm", "bip_upperArm_R", "RShoulderJ", "ShoulderR"),
            ("ValveBiped.Bip01_L_Forearm", "bip_lowerArm_L", "LArmJ", "ArmL"),
            ("ValveBiped.Bip01_R_Forearm", "bip_lowerArm_R", "RArmJ", "ArmR"),
            ("ValveBiped.Bip01_L_Hand", "bip_hand_L", "LHandN", "HandL"),
            ("ValveBiped.Bip01_R_Hand", "bip_hand_R", "RHandN", "HandR"),
            ("ValveBiped.Anim_Attachment_LH", "weapon_bone_L", "LHaveN", "HaveL"),
            ("ValveBiped.Anim_Attachment_RH", "weapon_bone_R", "RHaveN", "HaveR"),
            ("ValveBiped.Bip01_C_Thigh", "bip_hip_C", "CLegJ", "LegC"),
            ("ValveBiped.Bip01_L_Thigh", "bip_hip_L", "LLegJ", "LegL"),
            ("ValveBiped.Bip01_R_Thigh", "bip_hip_R", "RLegJ", "LegR"),
            ("ValveBiped.Bip01_L_Calf", "bip_knee_L", "LKneeJ", "KneeL"),
            ("ValveBiped.Bip01_R_Calf", "bip_knee_R", "RKneeJ", "KneeR"),
            ("ValveBiped.Bip01_L_Foot", "bip_foot_L", "LFootJ", "FootL"),
            ("ValveBiped.Bip01_R_Foot", "bip_foot_R", "RFootJ", "FootR"),
            ("ValveBiped.Bip01_L_Toe0", "bip_toe_L", "LToeN", "ToeL"),
            ("ValveBiped.Bip01_R_Toe0", "bip_toe_R", "RToeN", "ToeR"),
            # Fingers - Left Hand
            ("ValveBiped.Bip01_L_Finger1_Carpal", "bip_index_carpal_L", "LFingerBaseN", "FingerL10"),
            ("ValveBiped.Bip01_L_Finger2_Carpal", "bip_middle_carpal_L", "LMiddleN", "FingerL20"),
            ("ValveBiped.Bip01_L_Finger3_Carpal", "bip_ring_carpal_L", "LRingN", "FingerL30"),
            ("ValveBiped.Bip01_L_Finger4_Carpal", "bip_pinky_carpal_L", "LPinkyN", "FingerL40"),
            ("ValveBiped.Bip01_L_Finger1", "bip_index_0_L", "LIndex1N", "FingerL11"),
            ("ValveBiped.Bip01_L_Finger11", "bip_index_1_L", "LIndex2N", "FingerL12"),
            ("ValveBiped.Bip01_L_Finger12", "bip_index_2_L", "LIndex3N", "FingerL13"),
            ("ValveBiped.Bip01_L_Finger2", "bip_middle_0_L", "LMiddle1N", "FingerL21"),
            ("ValveBiped.Bip01_L_Finger21", "bip_middle_1_L", "LMiddle2N", "FingerL22"),
            ("ValveBiped.Bip01_L_Finger22", "bip_middle_2_L", "LMiddle3N", "FingerL23"),
            ("ValveBiped.Bip01_L_Finger3", "bip_ring_0_L", "LRing1N", "FingerL31"),
            ("ValveBiped.Bip01_L_Finger31", "bip_ring_1_L", "LRing2N", "FingerL32"),
            ("ValveBiped.Bip01_L_Finger32", "bip_ring_2_L", "LRing3N", "FingerL33"),
            ("ValveBiped.Bip01_L_Finger4", "bip_pinky_0_L", "LPinky1N", "FingerL41"),
            ("ValveBiped.Bip01_L_Finger41", "bip_pinky_1_L", "LPinky2N", "FingerL42"),
            ("ValveBiped.Bip01_L_Finger42", "bip_pinky_2_L", "LPinky3N", "FingerL43"),
            ("ValveBiped.Bip01_L_Finger0", "bip_thumb_0_L", "LThumb1N", "FingerL51"),
            ("ValveBiped.Bip01_L_Finger01", "bip_thumb_1_L", "LThumb2N", "FingerL52"),
            ("ValveBiped.Bip01_L_Finger02", "bip_thumb_2_L", "LThumb3N", "FingerL53"),
            # Fingers - Right Hand
            ("ValveBiped.Bip01_R_Finger1_Carpal", "bip_index_carpal_R", "RFingerBaseN", "FingerR10"),
            ("ValveBiped.Bip01_R_Finger2_Carpal", "bip_middle_carpal_R", "RMiddleN", "FingerR20"),
            ("ValveBiped.Bip01_R_Finger3_Carpal", "bip_ring_carpal_R", "RRingN", "FingerR30"),
            ("ValveBiped.Bip01_R_Finger4_Carpal", "bip_pinky_carpal_R", "RPinkyN", "FingerR40"),
            ("ValveBiped.Bip01_R_Finger1", "bip_index_0_R", "RIndex1N", "FingerR11"),
            ("ValveBiped.Bip01_R_Finger11", "bip_index_1_R", "RIndex2N", "FingerR12"),
            ("ValveBiped.Bip01_R_Finger12", "bip_index_2_R", "RIndex3N", "FingerR13"),
            ("ValveBiped.Bip01_R_Finger2", "bip_middle_0_R", "RMiddle1N", "FingerR21"),
            ("ValveBiped.Bip01_R_Finger21", "bip_middle_1_R", "RMiddle2N", "FingerR22"),
            ("ValveBiped.Bip01_R_Finger22", "bip_middle_2_R", "RMiddle3N", "FingerR23"),
            ("ValveBiped.Bip01_R_Finger3", "bip_ring_0_R", "RRing1N", "FingerR31"),
            ("ValveBiped.Bip01_R_Finger31", "bip_ring_1_R", "RRing2N", "FingerR32"),
            ("ValveBiped.Bip01_R_Finger32", "bip_ring_2_R", "RRing3N", "FingerR33"),
            ("ValveBiped.Bip01_R_Finger4", "bip_pinky_0_R", "RPinky1N", "FingerR41"),
            ("ValveBiped.Bip01_R_Finger41", "bip_pinky_1_R", "RPinky2N", "FingerR42"),
            ("ValveBiped.Bip01_R_Finger42", "bip_pinky_2_R", "RPinky3N", "FingerR43"),
            ("ValveBiped.Bip01_R_Finger0", "bip_thumb_0_R", "RThumb1N", "FingerR51"),
            ("ValveBiped.Bip01_R_Finger01", "bip_thumb_1_R", "RThumb2N", "FingerR52"),
            ("ValveBiped.Bip01_R_Finger02", "bip_thumb_2_R", "RThumb3N", "FingerR53"),
            # Helpers
            ("ValveBiped.Bip01_Neck_Twist", "hlp_neck", "HLP_neckJ", "H_Neck"),
            ("ValveBiped.Bip01_L_Bicep", "hlp_upperArm_L", "HLP_LSholJb", "H_ShoulderL"),
            ("ValveBiped.Bip01_R_Bicep", "hlp_upperArm_R", "HLP_RSholJb", "H_ShoulderR"),
            ("ValveBiped.Bip01_L_Bicep", "hlp_upperArm_L", "HLP_LSholJb", "H_SholderL"),  # Sometimes they have this spelling instead
            ("ValveBiped.Bip01_R_Bicep", "hlp_upperArm_R", "HLP_RSholJb", "H_SholderR"),  # !!!
            ("ValveBiped.Bip01_L_Ulna", "hlp_lowerArm_L", "HLP_LArmTwistjb", "H_ArmtwistL"),
            ("ValveBiped.Bip01_R_Ulna", "hlp_lowerArm_R", "HLP_RArmTwistJb", "H_ArmtwistR"),
            ("ValveBiped.Bip01_L_Wrist", "hlp_wrist_L", "HLP_LTekubiJb", "H_WristL"),
            ("ValveBiped.Bip01_R_Wrist", "hlp_wrist_R", "HLP_RTekubiJb", "H_WristR"),
            ("ValveBiped.Bip01_L_Quadricep", "hlp_hip_L", "HLP_LComaneciJb", "H_LegL"),
            ("ValveBiped.Bip01_R_Quadricep", "hlp_hip_R", "HLP_RComaneciJb", "H_LegR"),
            ("ValveBiped.Bip01_L_Calf", "hlp_knee_L", "HLP_LKneeJb", "H_KneeL"),
            ("ValveBiped.Bip01_R_Calf", "hlp_knee_R", "HLP_RKneeJb", "H_KneeR"),
            ("ValveBiped.Bip01_LFootTwist", "hlp_foot_L", "HLP_LFootJb", "H_FootL"),
            ("ValveBiped.Bip01_RFootTwist", "hlp_foot_R", "HLP_RFootJb", "H_FootR"),
            # Face
            ("ValveBiped.Bip01_Jaw", "prp_jaw", "FaceJawN", "Jaw"),
            ("ValveBiped.Bip01_Tongue", "prp_tongue", "FaceTongueN", "Tongue"),
            ("ValveBiped.Bip01_C_Lip_Upper", "prp_lip_upper_middle", "FaceCLipUpperN", "UplipC"),
            ("ValveBiped.Bip01_C_Lip_Lower", "prp_lip_lower_middle", "FaceCLipLowerN", "DownlipC"),
            ("ValveBiped.Bip01_L_Lip_Upper", "prp_lip_upper_L", "FaceLLipUpperN", "UplipL1"),
            ("ValveBiped.Bip01_R_Lip_Upper", "prp_lip_upper_R", "FaceRLipUpperN", "UplipR1"),
            ("ValveBiped.Bip01_L_Lip_Corner", "prp_mouth_corner_L", "FaceLLipCornerN", "UplipL2"),
            ("ValveBiped.Bip01_R_Lip_Corner", "prp_mouth_corner_R", "FaceRLipCornerN", "UplipR2"),
            ("ValveBiped.Bip01_L_Lip_Lower", "prp_lip_lower_L", "FaceLLipLowerN", "DownlipL"),
            ("ValveBiped.Bip01_R_Lip_Lower", "prp_lip_lower_R", "FaceRLipLowerN", "DownlipR"),
            # Skirt Swings
            ("ValveBiped.Bip01_F_Skirt0", "prp_skirt_front_1", "SWG_FSkirt0__swing", "S_SkirtF1"),
            ("ValveBiped.Bip01_F_Skirt1", "prp_skirt_front_2", "SWG_FSkirt1__swing", "S_SkirtF2"),
            ("ValveBiped.Bip01_F_Skirt2", "prp_skirt_front_3", "SWG_FSkirt2__swing", "S_SkirtF3"),
            ("ValveBiped.Bip01_F_Skirt3", "prp_skirt_front_4", "SWG_FSkirt3__swing", "S_SkirtF4"),
            ("ValveBiped.Bip01_B_Skirt0", "prp_skirt_back_1", "SWG_BSkirt0__swing", "S_SkirtB1"),
            ("ValveBiped.Bip01_B_Skirt1", "prp_skirt_back_2", "SWG_BSkirt1__swing", "S_SkirtB2"),
            ("ValveBiped.Bip01_B_Skirt2", "prp_skirt_back_3", "SWG_BSkirt2__swing", "S_SkirtB3"),
            ("ValveBiped.Bip01_B_Skirt3", "prp_skirt_back_4", "SWG_BSkirt3__swing", "S_SkirtB4"),
            ("ValveBiped.Bip01_L_Skirt0", "prp_skirt_1_L", "SWG_LSkirt0__swing", "S_SkirtL1"),
            ("ValveBiped.Bip01_L_Skirt1", "prp_skirt_2_L", "SWG_LSkirt1__swing", "S_SkirtL2"),
            ("ValveBiped.Bip01_L_Skirt2", "prp_skirt_3_L", "SWG_LSkirt2__swing", "S_SkirtL3"),
            ("ValveBiped.Bip01_L_Skirt3", "prp_skirt_4_L", "SWG_LSkirt3__swing", "S_SkirtL4"),
            ("ValveBiped.Bip01_R_Skirt0", "prp_skirt_1_R", "SWG_RSkirt0__swing", "S_SkirtR1"),
            ("ValveBiped.Bip01_R_Skirt1", "prp_skirt_2_R", "SWG_RSkirt1__swing", "S_SkirtR2"),
            ("ValveBiped.Bip01_R_Skirt2", "prp_skirt_3_R", "SWG_RSkirt2__swing", "S_SkirtR3"),
            ("ValveBiped.Bip01_R_Skirt3", "prp_skirt_4_R", "SWG_RSkirt3__swing", "S_SkirtR4"),
            ("ValveBiped.Bip01_BL_Skirt0", "prp_skirt_back_1_L", "SWG_LBSkirt0__swing", "S_SkirtBL1"),
            ("ValveBiped.Bip01_BL_Skirt1", "prp_skirt_back_2_L", "SWG_LBSkirt1__swing", "S_SkirtBL2"),
            ("ValveBiped.Bip01_BL_Skirt2", "prp_skirt_back_3_L", "SWG_LBSkirt2__swing", "S_SkirtBL3"),
            ("ValveBiped.Bip01_BL_Skirt3", "prp_skirt_back_4_L", "SWG_LBSkirt3__swing", "S_SkirtBL4"),
            ("ValveBiped.Bip01_BR_Skirt0", "prp_skirt_back_1_R", "SWG_RBSkirt0__swing", "S_SkirtBR1"),
            ("ValveBiped.Bip01_BR_Skirt1", "prp_skirt_back_2_R", "SWG_RBSkirt1__swing", "S_SkirtBR2"),
            ("ValveBiped.Bip01_BR_Skirt2", "prp_skirt_back_3_R", "SWG_RBSkirt2__swing", "S_SkirtBR3"),
            ("ValveBiped.Bip01_BR_Skirt3", "prp_skirt_back_4_R", "SWG_RBSkirt3__swing", "S_SkirtBR4"),
            ("ValveBiped.Bip01_FL_Skirt0", "prp_skirt_front_1_L", "SWG_LFSkirt0__swing", "S_SkirtFL1"),
            ("ValveBiped.Bip01_FL_Skirt1", "prp_skirt_front_2_L", "SWG_LFSkirt1__swing", "S_SkirtFL2"),
            ("ValveBiped.Bip01_FL_Skirt2", "prp_skirt_front_3_L", "SWG_LFSkirt2__swing", "S_SkirtFL3"),
            ("ValveBiped.Bip01_FL_Skirt3", "prp_skirt_front_4_L", "SWG_LFSkirt3__swing", "S_SkirtFL4"),
            ("ValveBiped.Bip01_FR_Skirt0", "prp_skirt_front_1_R", "SWG_RFSkirt0__swing", "S_SkirtFR1"),
            ("ValveBiped.Bip01_FR_Skirt1", "prp_skirt_front_2_R", "SWG_RFSkirt1__swing", "S_SkirtFR2"),
            ("ValveBiped.Bip01_FR_Skirt2", "prp_skirt_front_3_R", "SWG_RFSkirt2__swing", "S_SkirtFR3"),
            ("ValveBiped.Bip01_FR_Skirt3", "prp_skirt_front_4_R", "SWG_RFSkirt3__swing", "S_SkirtFR4"),
        ]
    ),
    "Link": (
        False,  # ClavicleC
        False,  # LegC
        [
            # Equipment
            ("ValveBiped.Bip01_Attachment_Slate", "prp_sheikah_slate", "SekibanN", "sheikahstone"),
            ("ValveBiped.Bip01_Attachment_Quiver", "prp_quiver", "YadutsuN", "queiver"),
            ("ValveBiped.Bip01_Attachment_Scabbard", "prp_scabbard", "SayaN", "Scabbard"),
            ("ValveBiped.Bip01_Attachment_Scabbard_Bow", "prp_scabbard_bow", "SayaYumiN", "BowB"),
            ("ValveBiped.Bip01_Attachment_Scabbard_Shield", "prp_scabbard_shield", "SayaTateN", "ShieldB"),
            ("ValveBiped.Bip01_Attachment_Scabbard_Sword", "prp_scabbard_sword", "SayaTukaN", "Hilt"),
            ("ValveBiped.Bip01_Attachment_Shield", "prp_shield", "TateN", "Shield"),
            ("ValveBiped.Bip01_Attachment_Sword0", "prp_sword_1", "KenJ", "Sword1"),
            ("ValveBiped.Bip01_Attachment_Sword1", "prp_sword_2", "KenModelN", "Sword2"),
        ]
    ),
    "Palutena": (
        True,  # ClavicleC
        True,  # LegC
        [
            # Hair
            ("ValveBiped.Bip01_L_Hair0", "prp_hair_1_L", "SWG_LHair0__swing", "S_HairBL1"),
            ("ValveBiped.Bip01_L_Hair1", "prp_hair_2_L", "SWG_LHair1__swing", "S_HairBL2"),
            ("ValveBiped.Bip01_L_Hair2", "prp_hair_3_L", "SWG_LHair2__swing", "S_HairBL3"),
            ("ValveBiped.Bip01_L_Hair3", "prp_hair_4_L", "SWG_LHair3__swing", "S_HairBL4"),
            ("ValveBiped.Bip01_R_Hair0", "prp_hair_1_R", "SWG_RHair0__swing", "S_HairBR1"),
            ("ValveBiped.Bip01_R_Hair1", "prp_hair_2_R", "SWG_RHair1__swing", "S_HairBR2"),
            ("ValveBiped.Bip01_R_Hair2", "prp_hair_3_R", "SWG_RHair2__swing", "S_HairBR3"),
            ("ValveBiped.Bip01_R_Hair3", "prp_hair_4_R", "SWG_RHair3__swing", "S_HairBR4"),
            ("ValveBiped.Bip01_L_Bangs0", "prp_hair_bangs_L", "SWG_LSHair0__swing", "S_HairL1"),
            ("ValveBiped.Bip01_R_Bangs0", "prp_hair_bangs_R", "SWG_RSHair0__swing", "S_HairR1"),
            # Staff / Shield
            ("ValveBiped.Bip01_Attachment_Staff", "prp_staff", "RStickN", "Stick"),
            ("ValveBiped.Bip01_Attachment_Shield", "prp_shield", "ShieldN", "Shield"),
            ("ValveBiped.Bip01_Attachment_Shield_String0", "prp_shield_string_1", "SWG_String0__swing", "S_String1"),
            ("ValveBiped.Bip01_Attachment_Shield_String1", "prp_shield_string_2", "SWG_String1__swing", "S_String2"),
        ]
    ),
    "Zelda": (
        True,  # ClavicleC
        True,  # LegC
        [
            # L/R Skirt chains are unique on the Wii U skeleton!
            ("ValveBiped.Bip01_L_Skirt0", "prp_skirt_1_L", "SWG_LSSkirt0__swing", "S_SkirtL1"),
            ("ValveBiped.Bip01_L_Skirt1", "prp_skirt_2_L", "SWG_LSSkirt1__swing", "S_SkirtL2"),
            ("ValveBiped.Bip01_L_Skirt2", "prp_skirt_3_L", "SWG_LSSkirt2__swing", "S_SkirtL3"),
            ("ValveBiped.Bip01_L_Skirt3", "prp_skirt_4_L", "SWG_LSSkirt3__swing", "S_SkirtL4"),
            ("ValveBiped.Bip01_R_Skirt0", "prp_skirt_1_R", "SWG_RSSkirt0__swing", "S_SkirtR1"),
            ("ValveBiped.Bip01_R_Skirt1", "prp_skirt_2_R", "SWG_RSSkirt1__swing", "S_SkirtR2"),
            ("ValveBiped.Bip01_R_Skirt2", "prp_skirt_3_R", "SWG_RSSkirt2__swing", "S_SkirtR3"),
            ("ValveBiped.Bip01_R_Skirt3", "prp_skirt_4_R", "SWG_RSSkirt3__swing", "S_SkirtR4"),
            # Hair Bangs
            ("ValveBiped.Bip01_L_Bangs0", "prp_hair_bangs_1_L", "SWG_LHair0__swing", "S_HairL1"),
            ("ValveBiped.Bip01_L_Bangs1", "prp_hair_bangs_2_L", "SWG_LHair1__swing", "S_HairL2"),
            ("ValveBiped.Bip01_L_Bangs2", "prp_hair_bangs_3_L", "SWG_LHair2__swing", "S_HairL3"),
            ("ValveBiped.Bip01_L_Bangs3", "prp_hair_bangs_4_L", "SWG_LHair3__swing", "S_HairL4"),
            ("ValveBiped.Bip01_R_Bangs0", "prp_hair_bangs_1_R", "SWG_RHair0__swing", "S_HairR1"),
            ("ValveBiped.Bip01_R_Bangs1", "prp_hair_bangs_2_R", "SWG_RHair1__swing", "S_HairR2"),
            ("ValveBiped.Bip01_R_Bangs2", "prp_hair_bangs_3_R", "SWG_RHair2__swing", "S_HairR3"),
            ("ValveBiped.Bip01_R_Bangs3", "prp_hair_bangs_4_R", "SWG_RHair3__swing", "S_HairR4"),
            # Hair
            ("ValveBiped.Bip01_B_Hair0", "prp_hair_back_1", "SWG_BHair0__swing", "S_HairB1"),
            ("ValveBiped.Bip01_B_Hair1", "prp_hair_back_2", "SWG_BHair1__swing", "S_HairB2"),
            ("ValveBiped.Bip01_B_Hair2", "prp_hair_back_3", "SWG_BHair2__swing", "S_HairB3"),
            ("ValveBiped.Bip01_B_Hair3", "prp_hair_back_4", "SWG_BHair3__swing", "S_HairB4"),
            ("ValveBiped.Bip01_BL_Hair0", "prp_hair_back_1_L", "SWG_BLHair0__swing", "S_HairBL1"),
            ("ValveBiped.Bip01_BL_Hair1", "prp_hair_back_2_L", "SWG_BLHair1__swing", "S_HairBL2"),
            ("ValveBiped.Bip01_BL_Hair2", "prp_hair_back_3_L", "SWG_BLHair2__swing", "S_HairBL3"),
            ("ValveBiped.Bip01_BL_Hair3", "prp_hair_back_4_L", "SWG_BLHair3__swing", "S_HairBL4"),
            ("ValveBiped.Bip01_BR_Hair0", "prp_hair_back_1_R", "SWG_BRHair0__swing", "S_HairBR1"),
            ("ValveBiped.Bip01_BR_Hair1", "prp_hair_back_2_R", "SWG_BRHair1__swing", "S_HairBR2"),
            ("ValveBiped.Bip01_BR_Hair2", "prp_hair_back_3_R", "SWG_BRHair2__swing", "S_HairBR3"),
            ("ValveBiped.Bip01_BR_Hair3", "prp_hair_back_4_R", "SWG_BRHair3__swing", "S_HairBR4"),
            # Pauldrons / Chestpiece
            ("ValveBiped.Bip01_L_Pauldron", "prp_pauldron_L", "Larmor", "ShoulderpadL"),
            ("ValveBiped.Bip01_R_Pauldron", "prp_pauldron_R", "Rarmor", "ShoulderpadR"),
            ("ValveBiped.Bip01_Breastplate", "prp_breastplate", "Bustarmor", "Breastplate"),
            # Loincloth <--> Apron
            ("ValveBiped.Bip01_Loincloth0", "prp_loincloth_1", "SWG_FMaedare0__swing", "S_Apron1"),
            ("ValveBiped.Bip01_Loincloth1", "prp_loincloth_2", "SWG_FMaedare1__swing", "S_Apron2"),
            ("ValveBiped.Bip01_Loincloth2", "prp_loincloth_3", "SWG_FMaedare2__swing", "S_Apron3"),
            ("ValveBiped.Bip01_Loincloth3", "prp_loincloth_4", "SWG_FMaedare3__swing", "S_Apron4"),
            # Ulti Zelda's Cape
            ("ValveBiped.Bip01_C_Cape0", "prp_cape_1_C", "SWG_BMantle0__swing", "S_MantleB1"),
            ("ValveBiped.Bip01_C_Cape1", "prp_cape_2_C", "SWG_BMantle1__swing", "S_MantleB2"),
            ("ValveBiped.Bip01_C_Cape2", "prp_cape_3_C", "SWG_BMantle2__swing", "S_MantleB3"),
            ("ValveBiped.Bip01_C_Cape3", "prp_cape_4_C", "SWG_BMantle3__swing", "S_MantleB4"),
            ("ValveBiped.Bip01_L_Cape0", "prp_cape_1_L", "SWG_BLMantle0__swing", "S_MantleL1"),
            ("ValveBiped.Bip01_L_Cape1", "prp_cape_2_L", "SWG_BLMantle1__swing", "S_MantleL2"),
            ("ValveBiped.Bip01_L_Cape2", "prp_cape_3_L", "SWG_BLMantle2__swing", "S_MantleL3"),
            ("ValveBiped.Bip01_L_Cape3", "prp_cape_4_L", "SWG_BLMantle3__swing", "S_MantleL4"),
            ("ValveBiped.Bip01_R_Cape0", "prp_cape_1_R", "SWG_BRMantle0__swing", "S_MantleR1"),
            ("ValveBiped.Bip01_R_Cape1", "prp_cape_2_R", "SWG_BRMantle1__swing", "S_MantleR2"),
            ("ValveBiped.Bip01_R_Cape2", "prp_cape_3_R", "SWG_BRMantle2__swing", "S_MantleR3"),
            ("ValveBiped.Bip01_R_Cape3", "prp_cape_4_R", "SWG_BRMantle3__swing", "S_MantleR4"),
            # Ulti Zelda's "Tassets"
            ("ValveBiped.Bip01_L_Tasset0", "prp_tasset_L", "SWG_LWaistmetal0__swing", "S_SkirtacceL1"),
            ("ValveBiped.Bip01_R_Tasset0", "prp_tasset_R", "SWG_RWaistmetal0__swing", "S_SkirtacceR1"),
        ]
    ),
}